# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_name', models.CharField(max_length=100)),
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_name', models.CharField(max_length=100)),
                ('employee_gender', models.CharField(max_length=20)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='department',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.employee'),
        ),
    ]
