# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudapp', '0005_auto_20171124_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.Employee'),
        ),
    ]
