# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20171124_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employee',
        ),
    ]
